implement aes256 file encryption #2
capsule-corp-ternoa/sgx-keyvault pull request #15
Opened 2021-06-24 16:24 UTC by echevrier

Add a decrypt function for testing.
Closes #2

2021-06-25 12:23 UTC, brenzi requested changes
I'd like to look at it again after the next iteration.

I suggest you also run `cargo clippy` and check warnings and suggestions

2021-06-25 12:23 UTC, brenzi commented on client/src/aes.rs
> +pub fn encrypt_aes256(filename: String) -> Result<()> {
I don't like this fn name because it doesn't say precisely what the function does but it hard-codes the cipher we're using, which I would not suggest.

What the function does is
* create an AES256 key if it doesn't exist yet
* encrypt the file passed as argument
* handle file IO (hidden behind AesEncryption)

I also don't like that the encryption assumes that the keyfile has the same name. Please check #1 where we will pass the decryption key differently than with a file with the same name

Therefore I'd suggest to split these functions (and use them separately in main.rs)
* `recover_or_generate_encryption_key(filename) -> key`
* `encrypt(plaintext_filename, Option<key>)`
* `decrypt(ciphertext_filename, Option<key>)`

The Option allows you to specify the key if you want. If `None`, you'll use file discovery by filename extension as you do now

2021-06-25 12:23 UTC, brenzi commented on client/src/aes.rs
> +pub struct Aes256Encryption {
This appears like "OO" thinking to me. I don't understand why you wrap this in its own struct. Its not wrong, just doesn't strike me as necessary nor helpful.

I would just have the private functions on module level directly and pass filenames as arguments.

2021-06-28 08:56 UTC, echevrier commented on client/src/main.rs
> +use crate::aes::encrypt_aes256;
The compiler was claiming ambiguity problems for aers. Changing the module name to cipher allows you to avoid using crate

2021-06-28 09:03 UTC, echevrier commented on client/src/main.rs
> +                .arg(
OK

2021-06-28 09:06 UTC, echevrier commented on client/src/main.rs
> +    let inputfile = format!("{}", matches.value_of("inputFile").unwrap());
ok

2021-06-28 09:29 UTC, echevrier commented on client/src/main.rs
> +}
OK

2021-06-29 09:19 UTC, echevrier commented on client/src/main.rs
> +mod aes;
OK

2021-07-01 15:39 UTC, echevrier commented on client/src/aes.rs
> +pub struct Aes256Encryption {
OK

2021-07-01 15:39 UTC, echevrier commented on client/src/aes.rs
> +pub fn encrypt_aes256(filename: String) -> Result<()> {
ok

2021-07-01 15:40 UTC, echevrier commented on client/src/main.rs
> +fn encrypt(matches: &ArgMatches<'_>) {
ok

2021-07-06 15:52 UTC, brenzi commented on client/src/cipher.rs
> +pub fn encrypt(plaintext_filename: &str, key: Option<Key>) -> Result<()> {
@echevrier please check this suggestion how to make cleaner use of paths

2021-07-06 15:54 UTC, brenzi commented on client/src/cipher.rs
> +            recover_encryption_key(
@echevrier if you try to decrypt without keyfile this should fail early. makes no sense in generating a key if it doesn't exists (check commit b28b11bf22

2021-07-06 15:55 UTC, brenzi commented on client/src/tests.rs
> +}
this is how I suggest to write tests involving files. There as a crate for this ;-)
The problem with your solution is that there are race conditions because tests run in parallel
Please clean this file up accordingly

2021-07-06 15:56 UTC, brenzi requested changes
please fix tests along example. Then I think the PR is good to go

2021-07-06 16:22 UTC, echevrier commented on client/src/cipher.rs
> +pub fn encrypt(plaintext_filename: &str, key: Option<Key>) -> Result<()> {
Cool. Thanks

2021-07-07 06:19 UTC, echevrier commented on client/src/cipher.rs
> +            recover_encryption_key(
Yes. this makes no sense

2021-07-07 09:17 UTC, echevrier commented on client/src/tests.rs
> +}
In my solution, I created a new directory for each test, which I deleted at the end, to avoid race conditions. The tempfile crate does it much better, which is what I was looking for.

2021-07-07 13:41 UTC, echevrier commented on client/src/tests.rs
> +}
Done. Please check.

2021-07-08 06:14 UTC, brenzi commented on client/src/cipher.rs
> +    Ok(())
no need to pass OK explicitly at the end. yust remove `?;` above

2021-07-08 06:15 UTC, brenzi commented on client/src/tests.rs
> +fn create_test_file(dir_path: &Path) -> std::io::Result<PathBuf> {
"test file" is a very meaningless name
what you create here is the `plaintext_input` IMO

2021-07-08 06:18 UTC, brenzi commented on client/src/tests.rs
> +const TEST_EN_FILE_EXT: &str = "ciphertext";
I'm no fan of unfamiliar abbreviations in variable/constant names. On the other hand, you can leave away fillers like `TEST`

what about
```
KEYFILE_EXT
CIPHERTEXT_EXT
DECRYPTED_EXT
```

2021-07-08 06:20 UTC, brenzi commented on client/src/tests.rs
> +fn try_read_file(decrypted_file_path: &str) -> std::io::Result<String> {
I'd leave the `assert!` to the test and not put it into helper functions. Just return an error if somethings wrong and then do the assertion in the test
Better readability of test and better debugging in case of failure (if cargo test tells you that this assertion failed, how do you know where in your test this helper has been called?)

2021-07-08 06:21 UTC, brenzi commented on client/src/tests.rs
> +    assert!(decrypted_read_result.is_ok());
dito

2021-07-08 06:22 UTC, brenzi commented on client/src/tests.rs
> +    let en_file_path = dir.path().join("input.".to_owned() + TEST_EN_FILE_EXT);
why `input`? Not all three files are input.

2021-07-08 06:24 UTC, brenzi commented on client/src/tests.rs
> +fn create_test_file(dir_path: &Path) -> std::io::Result<PathBuf> {
and if the argument was `PathBuf`, you wouldn't need to call `.to_path()` in the tests.

2021-07-08 06:25 UTC, brenzi commented on client/src/tests.rs
> +    let en_file_path = dir.path().join("input.".to_owned() + TEST_EN_FILE_EXT);
ah, sorry. In the flow of encryption and decryption it actually is correct to call the file input, because the rest is in the extension.....

2021-07-08 06:29 UTC, brenzi commented on client/src/tests.rs
> +    assert!(de_file_path.exists());
redundant. the above already checks that

2021-07-08 06:30 UTC, brenzi commented on client/src/tests.rs
> +    assert!(de_file_path.exists());
there are more of these redundancies in the tests

2021-07-08 06:30 UTC, brenzi requested changes
I might be overly picky, but here's what else I observe

2021-07-09 14:13 UTC, echevrier commented on client/src/tests.rs
> +const TEST_EN_FILE_EXT: &str = "ciphertext";
OK

2021-07-09 15:08 UTC, echevrier commented on client/src/tests.rs
> +fn try_read_file(decrypted_file_path: &str) -> std::io::Result<String> {
ok

2021-07-09 15:09 UTC, echevrier commented on client/src/tests.rs
> +    assert!(decrypted_read_result.is_ok());
OK

2021-07-09 15:16 UTC, echevrier commented on client/src/tests.rs
> +    assert!(de_file_path.exists());
Does this mean that if decrypt_result.is_ok() then the decrypted path file exists? So the assert!(decrypt_result.is_ok()); is sufficient?

2021-07-09 15:50 UTC, echevrier commented on client/src/tests.rs
> +fn create_test_file(dir_path: &Path) -> std::io::Result<PathBuf> {
As we use the TempDir now, we have to call path() or into_path(). Don't know what the best.

2021-07-09 16:03 UTC, echevrier commented on client/src/cipher.rs
> +    Ok(())
I think we have to do it, because we have to throw a "Cipher error".  I wrapped the different errors thrown by this method InvalidKeyNonceLength thrown by  AesOfb::new_var and the IoError.

2021-07-13 18:36 UTC, brenzi commented on client/src/tests.rs
> +    assert!(de_file_path.exists());
could the above succeed if the file wasn't there?

2021-07-13 18:40 UTC, brenzi commented on client/src/tests.rs
> +fn create_test_file(dir_path: &Path) -> std::io::Result<PathBuf> {
maybe I wasn't clear. why not
```
fn create_test_file(dir: &PathBuf) -> std::io::Result<PathBuf> {
```

2021-07-13 18:41 UTC, brenzi commented on client/src/tests.rs
> +fn try_read_file(decrypted_file_path: &str) -> std::io::Result<String> {
If you write "ok", please implement the change it in a commit and resolve the comment yourself. If I read "ok" but the code is still the same I don't know what to do

2021-07-13 19:01 UTC, brenzi commented
I don't want to keep this PR review for mere finetuning. @haerdib please merge if you think it should be merged

2021-07-14 13:21 UTC, echevrier commented on client/src/tests.rs
> +fn create_test_file(dir_path: &Path) -> std::io::Result<PathBuf> {
Now we have for the directory
```rust
let dir = tempdir().unwrap();
```
So we have to change it into
```rust
dir.path()
```
or
```rust
dir.into_path()
```

2021-07-14 17:54 UTC, haerdib approved these changes
I think this PR fulfills the task given in the issue, so I'm approving. My comments are mostly about coding style and opinions may differ there. 

We will need to find a consenuns on the general file structure (I'm not sure if a separate test file make sense here), but this discussion can be moved to a future task. It's more imporant now to finally merge the client tasks so we have a common ground before moving on to the non-client tasks.

2021-07-14 17:54 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_recover_or_generate_encryption_key() {
I guess there are as many opinions as there are developers, but here's how I understood the purpose of unit testing:
A unit test is about testing a specific functionality of the function (unit), not the function itself. Ideally, each unit test has only one pass / fail condition. Of course that's not always practically aplicable but it's a good guideline.

So in this specific case you're testing the function. However, the function has (as it's name suggests) more than one functionality. So I'd atleast expect two different unit tests for this function. Or more if the function also includes fail conditions: Every part of the function should be somwhen run through by unit tests.

Coming back to this function, the two most obvious unit tests would be:
1. does the function correctly recover the key given the necessary preconditions?
2. does the function correclty generate the key given the necessary preconditions?

and these tests (ideally) only answer this specific question and do not depend on anything else. Of course, always theoretically speaking. :)

2021-07-14 17:54 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_recover_or_generate_encryption_key() {
What I've read somewhere (though I don't remember the source anymore) is the tip to split the unit test in three parts: 
1. Preconditions ( `// given`)
2. The acutal function call you're testing ( `// when`)
3. The assertion part ( `//then`) 

This structure implicitely foces you to think about the question "What do I want to test"  (the when part) and clearly shows you when you've gone overboard and you're testing too many functionalities at once  (if the then part grows too large, there's probably something wrong).

2021-07-14 17:54 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_recover_or_generate_encryption_key() {
Personally, I think the guidelines written here are pretty spot on: https://esj.com/Articles/2012/09/24/Better-Unit-Testing.aspx?Page=1

2021-07-16 09:39 UTC, echevrier commented on client/src/ternoa_implementation/cipher.rs
> +pub type Key = (Vec<u8>, Vec<u8>);
Thanks, good input. I will not change the code now, but apply it in the future

2021-07-19 09:49 UTC, haerdib requested changes

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    let aes = re_result.ok().unwrap();
what is this for? Why are you converting a result into an option to unwrap it right away?
Why not simply call an unwrap like:
`let aes_key = recover_or_generate_encryption_key(&key_path).unwrap();`

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    let aes = result.ok().unwrap();
^^^^

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_generate_encryption_key() {
I don't see the difference of this test compared to the test above, expect an additional assert!() (line 49)

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(encrypt(inputfile_path.to_str().unwrap(), None).is_ok());
In this test it's not obvious what exactly you're testing. The reader can reason it by reading the title and searching for the name "encrypt" within the test function. 
At a first glance however is looks more lik you're testing the plaintext_input rather than the encrypt, because following the plaintext_input only assertions follow.

I think it would be much more obvious and faster to understand if you do not put the  encrypt call into an assert.

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(encrypt(inputfile_path.to_str().unwrap(), None).is_ok());
Here you're testing the encrypt command again with an assert. Why not simply call unwrap() which also ensures that an ok value was returned but does not imply that you're explicitely testing the encrypt function?

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(decrypt(ciphertext_path.to_str().unwrap(), None).is_ok());
Same as in the encrypt fuction

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    let aes = result.ok().unwrap();
^^^^

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(encrypt(test_file_path.to_str().unwrap(), Some(aes.clone())).is_ok());
^^^^

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(ciphertext_path.exists());
Would it not make sense to also read the file and ensure that the read key is the same you've actually defined above?
(same with default key I guess)

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_decrypt_with_key() {
Same comments as above

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(encrypt(file_path.to_str().unwrap(), None).is_ok());
no assert here. You're not testing this, an unwrap is enough

2021-07-19 09:49 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_decrypt_fails_with_diff_key() {
In this test it's also not clear what you're testing - you could simply remove some asserts and exchange with unwrap()

2021-07-20 12:21 UTC, echevrier commented on client/src/ternoa_implementation/tests.rs
> +fn verify_generate_encryption_key() {
The above test (verify_recover_encryption_key()) call 2 times the method recover_or_generate_encryption_key -> the first time to generate a key, the second time to recover it.

2021-07-20 12:42 UTC, echevrier commented on client/src/ternoa_implementation/tests.rs
> +    assert!(ciphertext_path.exists());
Does the key file have to be human readable? 
Is it not enough to test that the decryption fails, when we use different keys for encryption and decryption ? Test verify_decrypt_fails_with_diff_key()

2021-07-20 14:10 UTC, echevrier commented on client/src/ternoa_implementation/tests.rs
> +    assert!(ciphertext_path.exists());
Misunderstanding because of bad test name. Nothing to do with a default key and no key has to be checked.
The key file must also not be human readable. 
-> change test names into.
Encrypt and Decrypt method can be passed a key :
- verify_encrypt_passing_key()
- verify_decrypt_passing_key()
or None key:
- verify_encrypt_without_passing_key()
- verify_decrypt_without_passing_key(

2021-07-20 14:16 UTC, echevrier commented on client/src/ternoa_implementation/tests.rs
> +fn verify_decrypt_with_key() {
new test name : verify_decrypt_passing_key()

2021-07-21 09:54 UTC, haerdib requested changes
Only one small change requested, we can merge after this is fixed

2021-07-21 09:54 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_generate_encryption_key() {
Then, would it not make sense to test if the recovered key is the same as the previously generated key?

2021-07-21 09:54 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(ciphertext_path.exists());
Much better naming now :) Though "passing_key" is for me a key that passes a trial in the unit test or something. I think `input ` instead of `passsing ` would be a little bit clearer, but that's a trivial matter, you don't need to change.

2021-07-21 09:54 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    assert!(ciphertext_path.exists());
generally, don't cut the test names short. Feel free to use full sentences if necessary. `verify_decrypt_passing_key` is not really something a developer coming from outside is able to understand.

`verify_decrypt_fails_without_keyfile` however is very clear, nothing to misunderstand there I guess :)

2021-07-22 13:53 UTC, haerdib approved these changes
LGTM

2021-07-22 13:56 UTC, merged