1/ternoa client
capsule-corp-ternoa/sgx-keyvault pull request #16
Opened 2021-06-25 10:46 UTC by haerdib

Structure / outlayer of new cli commands

NOTE: This is not the final PR - ist just for showing the structure of the new cli calls.

2021-06-25 10:48 UTC, haerdib commented
@brenzi would you mind to take a look at the folder / file structure  and give some feedback if that's acceptable for you?

2021-06-26 13:14 UTC, brenzi requested changes
I think we should talk about this structural change. I'm not convinced it is the way to go.

2021-06-26 13:14 UTC, brenzi commented on client/src/ternoa_commands/decrypt.rs
> +fn command_runner<'a>(matches: &ArgMatches<'_>) -> Result<(), clap::Error> {
Could we improve testability if we extract matches before calling this function? "matches" seems like a very brittle interface abstraction to me
I'd unify this approach. right now we have a bit of a mess with this CLI (but I suggest to solve it properly upstream anyway: https://github.com/integritee-network/worker/issues/197

2021-06-26 13:14 UTC, brenzi commented on client/src/ternoa_commands/decrypt_shamir.rs
> +pub fn decrypt_shamir_cli_command() -> Command<'static, str> {
you deviate from the spec. why? In #1 the presence of the second positional argument is what defines if it is shamir or not. 
I'm not against separating this, but please update spec if you do.

2021-06-26 13:14 UTC, brenzi commented on client/src/ternoa_commands/decrypt_shamir.rs
> +            .required(true)
if you set this to false, a single subcommand would suffice

2021-06-26 13:14 UTC, brenzi commented on client/src/ternoa_commands/encrypt.rs
> +pub fn encrypt_cli_command() -> Command<'static, str> {
how does this go together with @echevrier's PR #15? We should define who adapts

2021-06-26 13:14 UTC, brenzi commented on substratee-client-primitives/src/common_args.rs
> +use clap::{App, Arg};
now you have clap all over the place. I don't like this.
I would prefer to have clap stuff only in one place: client/src/main.rs.
If need be in modules of that crate. Currently, its also in stf/src/cli which is already semi-cool. 
We should not spread that dep across even more crates.

2021-06-28 06:38 UTC, haerdib commented on client/src/main.rs
> +        .add_cmd(ternoa_commands::encrypt::encrypt_cli_command())
Hm.. I agree, the current hybrid way is not good. Should we create an issue regarding this matter or just leave it as is?

2021-06-28 06:42 UTC, haerdib commented on client/src/ternoa_commands/decrypt_shamir.rs
> +pub fn decrypt_shamir_cli_command() -> Command<'static, str> {
Oh, I see. I misunderstood that part then. Thanks for pointing it out.

2021-06-28 06:55 UTC, haerdib commented on substratee-client-primitives/src/common_args.rs
> +use clap::{App, Arg};
I agree on that, but how can be avoid duplicate code then? Because the client/main.rs depends on the [stf](https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/master/client/src/main.rs#L65) , cargo does not allow stf/cli.rs depend on client/main.rs : 

```bash
error: cyclic package dependency: package `substratee-stf v0.8.0 (/home/bhaerdi/ternoa/sgx-keyvault/stf)` depends on itself. Cycle:
package `substratee-stf v0.8.0 (/home/bhaerdi/ternoa/sgx-keyvault/stf)`
    ... which is depended on by `ternoa-client v0.8.0 (/home/bhaerdi/ternoa/sgx-keyvault/client)`
    ... which is depended on by `substratee-stf v0.8.0 (/home/bhaerdi/ternoa/sgx-keyvault/stf)`
Makefile:168: recipe for target 'bin/app' failed
```

So functions that are used on both sides can not be implemented in client/main.rs - or is there an option to go around this cargo restriction?

2021-06-28 07:20 UTC, haerdib commented on client/src/ternoa_commands/decrypt.rs
> +fn command_runner<'a>(matches: &ArgMatches<'_>) -> Result<(), clap::Error> {
That would definitely improve it. If we go along your suggestion from above, all commands in main.rs and all functionality somewhere different, that'd the way to go I guess. But lets leave this for https://github.com/integritee-network/worker/issues/197.

2021-06-30 13:18 UTC, haerdib commented on client/src/ternoa_commands/decrypt_shamir.rs
> +            .required(true)
Solved

2021-06-30 13:19 UTC, haerdib commented on client/src/ternoa_commands/decrypt_shamir.rs
> +pub fn decrypt_shamir_cli_command() -> Command<'static, str> {
solved

2021-06-30 13:19 UTC, haerdib commented on substratee-client-primitives/src/common_args.rs
> +use clap::{App, Arg};
solved by moving everything to the client folder

2021-06-30 13:20 UTC, haerdib commented on client/src/main.rs
> +        .add_cmd(ternoa_commands::encrypt::encrypt_cli_command())
Moved all new commands to a single file

2021-06-30 14:15 UTC, haerdib commented on client/src/ternoa_commands/encrypt.rs
> +pub fn encrypt_cli_command() -> Command<'static, str> {
We've agreed on the structure posted in #1

2021-07-01 07:37 UTC, ETeissonniere approved these changes
lgtm 🔥

2021-07-06 14:03 UTC, brenzi approved these changes

2021-07-06 14:03 UTC, merged