5/decryption
capsule-corp-ternoa/sgx-keyvault pull request #34
Opened 2021-07-23 14:10 UTC by echevrier

Client command line for decryption of secret with shami share

2021-07-24 11:53 UTC, haerdib requested changes
Some change requested. With PR #30 merged, after you've done a rebasing, can you remove the obsoletet url storage handler and make the keyvault client functions use the new storage handler?

Also add the appropriate function call to the provision call here: https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/develop/client/src/ternoa_implementation/keyvault/provision.rs#L45

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/decrypt.rs
> +use crate::ternoa_implementation::cipher::Key;
You now have a decrypt file but the decrypt function itself is not within this file..?
I think you should either place everything within cipher.rs or rename the files

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/decrypt.rs
> +fn aes256key_from_shamir_shares(
rename suggestion: `recover_aes256key_from_shamir_shares` or rename filename an make the function name shorter.

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +pub struct FileLocalStorage {
I think  "LocalFileStorage" makes more sense here

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +    fn set_filepath_works() {
renaming suggestion: `set_filename_and_path_works()`

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +
I know this is my bad, but could you add an assertion here, or a file remove command that the directory really does not exists before calling .`ensure_dir_exists()`?

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +pub trait StorageHandler<T> {
All this guy does it reading / writing lines to / from vectors, so a renaming suggestion:  `VecToLineConverter` or something that pictures what it actually does.

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +        assert_eq!(lines.len(), shares.len());
Not saying that what you're doing is wrong, but I think it would be enough to just assert that lines and shares are equal.

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +        // when
remove one

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +    let shares = shamir_shares(aes256_key.clone(), (THRESHOLD_SHAMIR_SHARE - 1) as usize);
Why are you testing a function that is only used in testing?

2021-07-24 11:53 UTC, haerdib commented on client/src/ternoa_implementation/tests.rs
> +fn verify_number_of_created_shares() {
^^^^

2021-07-24 14:30 UTC, haerdib commented
Could you also add a function to the Storage handler that allowed to write one line to a file only?
https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/develop/client/src/ternoa_implementation/keyvault/get.rs#L23
will need such a function to somehow store a keyvault response.

2021-07-26 08:36 UTC, echevrier commented on client/src/ternoa_implementation/decrypt.rs
> +fn aes256key_from_shamir_shares(
Sorry decrypt file should be deleted. Everything is in cipher.cs.

2021-07-26 08:36 UTC, echevrier commented on client/src/ternoa_implementation/decrypt.rs
> +use crate::ternoa_implementation::cipher::Key;
Sorry decrypt file should be deleted. Everything is in cipher.cs.

2021-07-26 08:36 UTC, echevrier commented on client/src/ternoa_implementation/decrypt.rs
> +    recovery_number_n: u8,
Sorry decrypt file should be deleted. Everything is in cipher.cs.

2021-07-26 08:58 UTC, echevrier commented on client/src/ternoa_implementation/decrypt.rs
> +    recovery_number_n: u8,
The corresponding valid method is aes256key_from_shamir_shares in cipher.rs: `aes256key_from_shamir_shares(shares: Vec<Share>, threshold_shares_num: u8)`. The threshold num is required  to initialize the Sharks.

2021-07-26 09:01 UTC, echevrier commented on client/src/ternoa_implementation/local_storage_handler.rs
> +pub struct FileLocalStorage {
Yes

2021-07-26 09:11 UTC, echevrier commented on client/src/ternoa_implementation/local_storage_handler.rs
> +
I'm not sure this is necessary, as the directory created in this test is deleted ("cleaned up") at the end.

2021-07-26 09:20 UTC, echevrier commented on client/src/ternoa_implementation/local_storage_handler.rs
> +pub trait StorageHandler<T> {
OK: VecToLinesConverter

2021-07-26 09:23 UTC, echevrier commented on client/src/ternoa_implementation/local_storage_handler.rs
> +        assert_eq!(lines.len(), shares.len());
What about if an additional line has been generated?

2021-07-26 09:30 UTC, echevrier commented on client/src/ternoa_implementation/tests.rs
> +    let shares = shamir_shares(aes256_key.clone(), (THRESHOLD_SHAMIR_SHARE - 1) as usize);
To be sure that the used method works and we can base the other test on it.

2021-07-26 09:36 UTC, echevrier commented on client/src/ternoa_implementation/cipher.rs
> +    let encryption_key = aes256key_from_shamir_shares(shares, SHAMIR_SHARES_THRESHOLD)?;
OK. The how does the client choose it?

2021-07-27 08:21 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +
Hm.. ok, I agree. Let's leave it like that.

2021-07-27 09:02 UTC, echevrier commented on client/src/ternoa_implementation/cipher.rs
> +    let encryption_key = aes256key_from_shamir_shares(shares, SHAMIR_SHARES_THRESHOLD)?;
The threshold is not needed in the recover key function `aes256key_from_shamir_shares`. I removed it.
If the number of provided shares is lower than the threshold set in the generation of the shamir shares the recovered key will be wrong.

2021-07-27 09:10 UTC, echevrier commented on client/src/ternoa_implementation/local_storage_handler.rs
> +        assert_eq!(lines.len(), shares.len());
I can't do something like `assert_eq!(lines, shares);` because the trait `std::fmt::Debug` is not implemented for `sharks::Share`

2021-07-27 09:25 UTC, haerdib commented on client/src/ternoa_implementation/local_storage_handler.rs
> +        assert_eq!(lines.len(), shares.len());
I see. But it would be possible to transform the Shares into Vec<u8> with `Vec::from(&shares)` (https://docs.rs/sharks/0.5.0/sharks/struct.Share.html) I guess.
But you don't need to change this. It's perfectly fine how you did it.

2021-07-27 15:48 UTC, echevrier commented
Close this pull request and created a new one due to the creation of a new branch to fix problem with rebase on the develop branch.
New Pull request #39

2021-07-27 15:48 UTC, closed without merging