8/keyvault store load
capsule-corp-ternoa/sgx-keyvault pull request #35
Opened 2021-07-23 14:53 UTC by echevrier

Store and load keyshare functionalities + unit test
TODO:
- Authorization : waiting for #7
- If import crate sharks::Share possible, change fct argument for Share

2021-07-24 13:17 UTC, haerdib requested changes
I might have been a little to early with my review, but I wanted to ensure you've enough work on monday :)

2021-07-24 13:17 UTC, haerdib commented on enclave/src/keyvault.rs
> +pub fn test_sealed_file_encode_nftid() {
just from reading this name I'm not able to understand what this function does - maybe rename?

2021-07-24 13:17 UTC, haerdib commented on enclave/src/keyvault.rs
> +pub fn test_share_saved_in_sealed_file() {
Here you're testing seal and unseal in one go. Maybe you could test seal first without depending on unseal?

2021-07-24 13:17 UTC, haerdib commented on enclave/src/keyvault.rs
> +
It'd be great to have a test the behaviour of unseal in case of file not existing

2021-07-24 13:17 UTC, haerdib commented on enclave/src/keyvault.rs
> +pub fn test_seal_override_existing_sealed_file() {
nice test! Just again the naming part : you have twice a "seal" in the name but the exected behaviour is not written down.
So the first question I asked myself when reading the test: Should this test ensure that overriding fails or that overriding works? Please clarify

2021-07-26 11:49 UTC, echevrier commented on enclave/src/keyvault.rs
> +        file_name.unwrap().is_file()
Actually sealed_file should not return a Result but the PathBuf.

2021-07-26 11:51 UTC, echevrier commented on enclave/src/keyvault.rs
> +fn sealed_filepath(path: &str, nft_id: NFTId) -> SgxResult<PathBuf> {
No error can be return by `sealed_filepath`. -> return PathBuf

2021-07-26 12:01 UTC, echevrier commented on enclave/src/keyvault.rs
> +fn sealed_filepath(path: &str, nft_id: NFTId) -> SgxResult<PathBuf> {
What about : `nft_sealed_file_path(path: &str, nft_id: NFTId)`, which means the path to the sealed file of a NFT? Like a variable, without the verb create or get.

2021-07-26 12:37 UTC, echevrier commented on enclave/src/keyvault.rs
> +pub fn test_sealed_file_encode_nftid() {
test_sealed_file_name_contains_nftid ?

2021-07-26 12:42 UTC, echevrier commented on enclave/src/keyvault.rs
> +pub fn test_share_saved_in_sealed_file() {
To be sure that the share is sealed in the file I have to unseal it and compare the obtained share with the original one.

2021-07-26 13:12 UTC, echevrier commented on enclave/src/keyvault.rs
> +pub fn test_share_saved_in_sealed_file() {
I add a test `test_seal_create_file`, which check that the sealed file is created

2021-07-26 13:13 UTC, echevrier commented on enclave/src/keyvault.rs
> +
This is done in `test_get_fails_when_nft_not_in_store`, but for more modularity, pehaps we should add a test `test_unseal_fails_when_no_file_exists`.

2021-07-26 13:18 UTC, echevrier commented on enclave/src/keyvault.rs
> +pub fn test_seal_override_existing_sealed_file() {
what about `test_seal_overrides_existing_sealed_file`? = seal overrides existing sealed file. Is it clearer?

2021-07-26 13:30 UTC, echevrier commented on enclave/src/keyvault.rs
> +pub fn test_seal_override_existing_sealed_file() {
**Important question about this**: This is the current behaviour: we can only seal 1 share in a file called `nft_id_Nft.bin` by calling `provision(owner: AccountId32, nft_id: NFTId, share: Share)`. I'm not sure this makes sense:
If we override it accenditaly, we loose the previous valid shares:
And what happens if someone has more then one share? Are there all in the same file? In this case how do we want to handle it?

2021-07-27 08:13 UTC, haerdib commented on enclave/src/keyvault.rs
> +
Ah I see. I think it would be gread to have an unseal unit test, in case later on an additional function will be using this function.

2021-07-27 08:14 UTC, haerdib commented on enclave/src/keyvault.rs
> +pub fn test_seal_override_existing_sealed_file() {
For the PoC I think overwriting with a `warn!` log message should be sufficient. For one keyvault we will have only one share per nftid.

2021-07-27 08:17 UTC, haerdib commented on enclave/src/keyvault.rs
> +pub fn test_seal_override_existing_sealed_file() {
> what about `test_seal_overrides_existing_sealed_file`? = seal overrides existing sealed file. Is it clearer?
Much better. I think `test_seal_overrides_existing_file` is enough, but your version is also ok.

2021-07-27 13:33 UTC, echevrier commented on enclave/src/keyvault.rs
> +    pub fn provision(owner: AccountId32, nft_id: NFTId, share: Vec<u8>) -> SgxResult<()> {
I implemented an error wrapper.

2021-07-28 11:13 UTC, haerdib requested changes

2021-07-28 11:13 UTC, haerdib commented on enclave/src/keyvault.rs
> +    pub fn test_provision_fails_when_no_nft_owner() {
You might have to think about writing a mock trait / struct function for `is_authorized`. Otherwise you will not be able to unit test these things.

I.e. create a trait which defines  `is_authorized and create a mock struct implementing this trait. Ideally you can choose the output of the is_authorized mock function when initialising the mock struct, so you can test failing and passing case.

2021-07-28 11:13 UTC, haerdib commented on enclave/src/keyvault.rs
> +const ALICE_ENCODED: [u8; 32] = [
You only need this for testing, so you could move into the `mod test`

2021-07-28 11:41 UTC, echevrier commented on enclave/src/keyvault.rs
> +//TODO: check if import of crate shark:share is possible. Wait for haerdib answer
yes

2021-07-28 17:16 UTC, haerdib approved these changes
LGTM

2021-07-28 17:21 UTC, merged