4/provision file reading
capsule-corp-ternoa/sgx-keyvault pull request #38
Opened 2021-07-24 16:15 UTC by haerdib

provision call now reads key from file, closes #4

2021-07-26 14:22 UTC, echevrier requested changes

2021-07-26 14:22 UTC, echevrier commented on client/src/ternoa_implementation/keyvault/provision.rs
> +    let key = cipher::recover_encryption_key(&cipher::keyfile_path(key_file))
If the input `key_file` is the key file, why do you call `keyfile_path(key_file)`? Method `keyfile_path(plaintext_filename: &str) -> PathBuf` is to generate the "default" key file from the input file path. This input file ist the file to encrypt or the file to decrypt and the default key file has the same name but an aes256 extension.
You only have to generate the PathBuf from the input str : `PathBuf::from(key_file)`;

2021-07-26 14:22 UTC, echevrier commented on client/src/ternoa_implementation/cipher.rs
> +pub fn keyfile_path(plaintext_filename: &str) -> PathBuf {
Make it public only if you really need it. See comment below, where you call it

2021-07-27 07:02 UTC, haerdib commented on client/src/ternoa_implementation/keyvault/provision.rs
> +    let key = cipher::recover_encryption_key(&cipher::keyfile_path(key_file))
because this function automatically ensures that the file has an .aes256 extension. However, in the thought of having different keys later on this ensurance doesn't make sense. I'll change accordingly.

2021-07-27 12:27 UTC, echevrier approved these changes

2021-07-27 13:05 UTC, merged